### PR TITLE
Fix CTYPE2 value

### PR DESCRIPTION
**Pull request by phsilva**

### CODE REVIEW

**Comment by phsilva** [comment]
To fix #73

**Comment by tribeiro** [comment]
:+1: 

Any particular reason not to merge it?

**Comment by phsilva** [comment]
not really, just didn't tested on wcslib. but code is mostly harmless.

**Comment by tribeiro** [comment]
ok... give me a sec... I'll test it...

**Comment by tribeiro** [comment]
flawless! :smile:

**Comment by phsilva** [comment]
great. merging and closing #73

**Pull request merged**
