### PR TITLE
Removed old autoguider files.

### PR DESCRIPTION
**Pull request by tribeiro**
Removing unfinished old auto guider files. Development was moved to an external plugin.

### CODE REVIEW

**Comment by phsilva** [comment]
I think the guider interface must stay in chimera main repo. Specially because we can have many implementations of autoguiders.

**Comment by tribeiro** [comment]
You mean the guider interface alone or the controller implementation as well?

**Comment by phsilva** [comment]
the guider interface alone, otherwise other implementors will have to define their own and the whole point of having interfaces go away.

**Comment by tribeiro** [comment]
Ok, got it... Well though...

**Comment by tribeiro** [comment]
(new) interface added.

**Comment by phsilva** [comment]
good. merge as you wish.

**Comment by wschoenell** [comment]
Merged #75.

**Pull request merged**
