### PR TITLE
Add new base instrument "Fan".

### PR DESCRIPTION
**Pull request by tribeiro**
* Add interface domefan
* Add instrument domefan and fakedomefan
* Modify chimera-dome to enable control of dome fan (optional) and to show information about fan if present.

Now, I understand this will probably create a lot of heated discussions around here (one more!). I initially though to include the domefan as an instance of dome. Problem is, you can easily have more then one dome fans installed and may want to control them independently. I could not though of a better way of doing it then to create a separate instrument (like filterwheel and camera).

### CODE REVIEW

**Comment by wschoenell** [comment]
I think that we could move to a more general instrument `Fan` which could be dome, telescope, etc...

**Comment by wschoenell** [comment]
Please add a configuration example to the fake instrument here:
https://github.com/astroufsc/chimera/blob/37c8bd88f66f3f8e59e569f92ad09e6cdb8eeb9a/src/chimera/core/chimera.sample.config

Can you sort/group better the help options?

```
...
  Commands:
    --info              Print dome information
    --openFlap          Open dome flap
    --to=AZ             Move dome to AZ azimuth
    --setFanSpeed=SPEED
                        Set fan speed.
    --openSlit          Open dome slit
    --track             Track the telescope
    --startFan          Start dome fan
    --stopFan           Stop dome fan
    --closeFlap         Close dome flap
    --stand             Stop tracking the telescope (stand)
    --getFanSpeed       Print dome information
    --closeSlit         Close dome slit
...
```

**Comment by tribeiro** [comment]
Done

**Comment by wschoenell** [comment]
Still pending the help order...

**Comment by tribeiro** [comment]
Didn't saw that part...

Em ter, 10 de nov de 2015 às 14:52, William Schoenell <
notifications@github.com> escreveu:

**Comment by tribeiro** [comment]
Ok, separated the actions on different groups.

**Comment by wschoenell** [comment]
I did some adaptions to this on my branch which I think that settle this PR.

* Renamed CalibrationLamp to simply Lap
* Created a new interface Switch which both Fan and Lamp interfaces inherit
* Added `fans` configuration option to telescope
* Added `fans` and `lamps` configuration option to telescope
* Added to `chimera-dome` fan and reformatted lamp control options:
```
  Dome lights control:
    --light-off         Turn light off
    --light-on          Turn light on
    --light-intensity=INTENSITY
                        Set light intensity to specified value.
    --lamp=LAMP         Calibration lamp to be used. [default=/Lamp/0]
...
  Dome Fans control:
    --fan-on            Start dome fan
    --fan-off           Stop dome fan
    --fan-speed=SPEED   Set fan speed.
    --fan=FAN           Fan instrument to be used. [default=/Fan/0]
```
* Added to `chimera-tel` fan control options:
```
  Telescope fan control:
    --fan-on            Start telescope fan
    --fan-off           Stop telescope fan
    --fan-speed=SPEED   Set fan speed.
    --fan=FAN           Fan instrument to be used. [default=/Fan/0]
```
* Reformatted `--info` output for `chimera-tel` and `chimera-dome`:
screen shot 2016-04-13 at 8 50 49 pm
screen shot 2016-04-13 at 8 50 32 pm


One example of configuration for a dome and a telescope with fans/lamps:
``` yaml
telescope:
  name: fake
  type: FakeTelescope
  fans: ['/FakeFan/fakefan_tel']

dome:
  name: fake
  type: FakeDome
  mode: track
  telescope: /FakeTelescope/fake
  lamps: ['/FakeLamp/fake1']
  fans: ['/FakeFan/fake1', '/FakeFan/fake2']

lamps:
  - name: fake1
    type: FakeLamp
    dome_az: 0
    telescope_alt: 90
    telescope_az: 45

  - name: fake2
    type: FakeLamp
    dome_az: 10
    telescope_alt: 90
    telescope_az: 55

fans:
  - name: fake1
    type: FakeFan

  - name: fake2
    type: FakeFan

  - name: fakefan_tel
    type: FakeFan

```

**Comment by wschoenell** [comment]
Tested on T80 and on fake instrument. All working fine.

**Pull request merged**
