### PR TITLE
Dome subclasses

### PR DESCRIPTION
**Pull request by tribeiro**
Subclass dome in order to separate the different properties of observatory domes. This is an intermediate commit aimed at providing support for fans and other optional attributes.

### CODE REVIEW

**Comment by phsilva** [comment]
I like it, very narrow interfaces make it easier to integrate very different styles of instruments. Nice job.

**Comment by wschoenell** [comment]
It breaks the FakeDome instrument, and probably the other domes.

	29-03-2015 13:20:48.889 [[localhost:7666]] INFO chimera.controllers.site.main main.py:231 Trying to start instruments...
	29-03-2015 13:20:49.125 [[localhost:7666]] INFO chimera.core.manager manager.py:530 Starting /FakeTelescope/fake.
	29-03-2015 13:20:49.126 [[localhost:7666]] INFO chimera.core.manager manager.py:547 Running /FakeTelescope/fake. __main___.
	29-03-2015 13:20:50.345 [[localhost:7666]] INFO chimera.core.manager manager.py:530 Starting /FakeCamera/fake.
	29-03-2015 13:20:50.345 [[localhost:7666]] INFO chimera.core.manager manager.py:547 Running /FakeCamera/fake. __main___.
	29-03-2015 13:20:50.348 [[localhost:7666]] INFO chimera.core.manager manager.py:530 Starting /FakeFocuser/fake.
	29-03-2015 13:20:50.348 [[localhost:7666]] INFO chimera.core.manager manager.py:547 Running /FakeFocuser/fake. __main___.
	Traceback (most recent call last):
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/controllers/site/main.py", line 255, in _add
		self.manager.addLocation(location, path, start)
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/core/manager.py", line 414, in addLocation
		cls = self.classLoader.loadClass(location.cls, path)
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/core/classloader.py", line 35, in loadClass
		return self._lookupClass(clsname, path)
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/core/classloader.py", line 86, in _lookupClass
		"Module %s found but couldn't be loaded." % clsname)
	ClassLoaderException: Module FakeDome found but couldn't be loaded.

	Caused by: Traceback (most recent call last):
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/core/classloader.py", line 58, in _lookupClass
		clsname.lower(), globals(), locals(), [clsname])
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/instruments/fakedome.py", line 26, in <module>
		from chimera.instruments.dome import DomeBase
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/instruments/dome.py", line 37, in <module>
		class DomeBase(ChimeraObject, Dome, DomeSlew, DomeSlit, DomeLights, DomeSync):
	  File "/Users/william/.virtualenvs/chimera/lib/python2.7/site-packages/chimera/core/metaobject.py", line 97, in __new__
		return super(MetaObject, meta).__new__(meta, clsname, bases, _dict)
	TypeError: Error when calling the metaclass bases
		Cannot create a consistent method resolution
	order (MRO) for bases DomeSlit, Interface, DomeSlew, Dome, DomeSync, DomeLights

**Comment by nsaavedra-naircl** [comment]
This looks a lot like an issue we had with the filter wheels driver… The error seems to refer to the “mro”: method resolution order. I’d suggest looking into the chain of inherited objects for duplicate method names as 1st step.

**Comment by tribeiro** [comment]
The problem is that class DomeBase is inheriting Dome along with all the other Dome submodule. If you take Dome from DomeBase it works.. 

```python
class DomeBase(ChimeraObject, Dome, DomeSlew, DomeSlit, DomeLights, DomeSync):
```

should be 

```python
class DomeBase(ChimeraObject, DomeSlew, DomeSlit, DomeLights, DomeSync):
```

I'll ask him to push the commit asap...

**Comment by wschoenell** [comment]
Now it works. Thanks!

Merged.

**Pull request merged**
