### PR TITLE
Fix chimera-focus and chimera-tel

### PR DESCRIPTION
**Pull request by wschoenell**
This PR fixes the chimera-focus and chimera-tel bugs introduced by #33. I've rolled back the chimera-focus to pre-PR, changed the c_open and close to openCover() and likewise. I also fixed the cover help on chimera-tel.

### CODE REVIEW

**Comment by tribeiro** [comment]
Please! Remove all changes made to

M src/chimera/instruments/astelco.py (4)
M src/chimera/instruments/telescope.py (4)
M src/scripts/chimera-tel (9)

before merging... I have a code revision almost ready for submission and this will make things much harder!

**Comment by wschoenell** [comment]
Hi Tiago,

I can merge this now and, then, merge your code as well. There is no
problem on doing that. If there are conflicts, they can be easily solved by
merging manually. I can do that.

William

**Comment by tribeiro** [comment]
I have a different proposal for including the telescope cover operations. Check my branch AstelcoRev.

**Comment by wschoenell** [comment]
There is still no chimera-tel fix on this branch that you have.

**Comment by tribeiro** [comment]
Done...

**Comment by wschoenell** [comment]
Merged #51. It fixes bugs introduced by #33 on chimera-tel and chimera-focus.

**Pull request merged**
