### PR TITLE
Fixes issue #39.

### PR DESCRIPTION
**Pull request by tribeiro**
Fixes issue #39. Implemented function __setitem__ in core.proxy.Proxy.

### CODE REVIEW

**Comment by phsilva** [comment]
Looks good to me. Have you checked on chimera-dome?

**Comment by phsilva** [comment]
I mean, does it fix the original --track issue?

**Comment by tribeiro** [comment]
Yes Sir... on chimera dome and other instruments... But now, indeed, it provides a more general (and elegant) solution...

>[tiago@lswlan61:~]% chimera-dome --track
 Activating tracking ...  OK 
 [tiago@lswlan61:~]% chimera-dome --track --telescope /Telescope/0 
 Activating tracking ...  OK 
 [tiago@lswlan61:~]% chimera-dome --track --telescope /Telescope/1 
 Activating tracking ...  OK 
 [tiago@lswlan61:~]% foo.py --start
 Fake Telescopes Inc.
 bar

**Comment by wschoenell** [comment]
Tested here too and it works. Merged.
	(chimera)Williams-MacBook-Pro:20150326 william$ chimera-dome --track
	Activating tracking ...  OK 
	(chimera)Williams-MacBook-Pro:20150326 william$ chimera-dome --stand
	Deactivating tracking ...  OK 
	(chimera)Williams-MacBook-Pro:20150326 william$ chimera-dome --track
	Activating tracking ...  OK

**Comment by phsilva** [comment]
Nice. Good we find a way.

**Pull request merged**
