### PR TITLE
Fli

### PR DESCRIPTION
**Pull request by nsaavedra-naircl**
This is the current, working version of the FLI camera, installed at t80s.

### CODE REVIEW

**Comment by nsaavedra-naircl** [comment]
Forgot to merge master 1st...

**Comment by nsaavedra-naircl** [comment]
ALso added an untested FLI filter wheel module. Upstream master has been merged into this branch, it should now be easier (!) to pull.

**Comment by phsilva** [comment]
@nsaavedra-naircl, I will review during the weekend, mostly for style or potential refactors as I can't test it on hardware.

**Comment by wschoenell** [comment]
Hold on a bit... I did some modifications on this code last friday to
install on a camera at CEFCA. I've installed yesterday and there are still
few details to fix.

**Comment by wschoenell** [comment]
The content of this chimera module was moved to a plugin on this repository: https://github.com/astroufsc/chimera-fli

Closed #57.

**Pull request closed without merging**
