### PR TITLE
Chimera plugins

### LINKED ISSUE #56: [PROPOSAL] Changes to the install procedure (setup.py)
Lately Chimera has been in need to incorporate packages, modules, libs, etc., that are not as much in PyPi as they reside in repos like github. Examples are the SI drivers, the AVT libraries and APIs, and the FLI camera lib. So far we have been either doing manual installs from each packages setup.py, or incorporating the code within the chimera structure.
The easiest  (imho) way to support this would be to use the "dependency_links" feature of setuptools. Another way would be to use git submodules, but I think this is less straightforward for non git savvy users.

### PR DESCRIPTION
**Pull request by wschoenell**
Makes chimera look for instruments and controllers in all python modules which name starts with ``chimera_``. A template example can be found on the link below. Fixes #56.

https://github.com/astroufsc/chimera_template

### CODE REVIEW

**Comment by tribeiro** [comment]
I have to say that I enjoyed this idea very much and I think it is a good move for chimera! I've been playing with this branch for a while, migrating astelco drivers, and it works pretty well. I vouch for this PR to be accepted soon rather than latter. It may be a good idea to clean it from the drivers before that. At least the astelco and SI.

**Comment by wschoenell** [comment]
If nobody manifests against until the end of the week, we can merge this. The driver cleanup can be done on further (and separated) PRs.

**Comment by phsilva** [comment]
@wschoenell, great work on this. I think it is mostly what I think it should be, just one questions before we merge:

 * Can we rename all outside projects to chimera-XXX instead of chimera_XXX? While the python package name for it must have the "_" the folder name seems to be clearer with a "-".

Are you going to remove the code that is now in plugins from Chimera after this PR?

**Comment by wschoenell** [comment]
@phsilva,

* I agree that chimera- is better. I will change on the plugins.

* After closing this PR I will release others cleaning up this one and, we can in the future move this repo for chimera-core and do the same on pypi registry. Something for further discussion...

**Comment by wschoenell** [comment]
I've changed the names of the repositories to the standard `chimera-nonono`. Will merge and close this. There is no need to change anything since the python modules (which are used on the search of plugins) will remain on `chimera_nonono` standard due to the Python package naming standards.

**Pull request merged**
