### PR TITLE
Add `getSideOfPier` to the telescope instrument interface

### PR DESCRIPTION
**Pull request by wschoenell**
Adds `getSideOfPier` to the telescope instrument interface

### CODE REVIEW

**Comment by tribeiro** [comment]
I would suggest the function to be named as

getPierSide instead of getSideOfPier...
Em qui, 4 de fev de 2016 às 08:53, William Schoenell <
notifications@github.com> escreveu:

**Comment by wschoenell** [comment]
Done on 57400c4e69c3b5c07b08f03869ad58c7698f5857

**Comment by tribeiro** [comment]
Sorry to disturb even further. Just a small consideration. What would be
the expected behavior in case the telescope does not have a side? Like in
altaz mounts? Should there be another option, like "undefined" or rise an
exception? Thinking ahead, it looks like a good job for the new "features"
scheme we are implementing.
Em qui, 4 de fev de 2016 às 09:13, William Schoenell <
notifications@github.com> escreveu:

**Comment by ankanaan** [comment]
I think undefined is better than raising an exception, by the way, I
suggest, EAST, WEST, CENTER (for altaz)

**Comment by wschoenell** [comment]
Following your suggestions, I moved out the pier interface from the telescope interface. The method (if exists) should return one EAST/WEST/UNKNOWN following the ASCOM standard.

**Pull request merged**
