### PR TITLE
Astelco revision

### PR DESCRIPTION
**Pull request by tribeiro**
A revised (again) version of the astelco software. This provides much better slewing operation and much reliable parking/unparking. If unpacking fails (which happens from time to time), it will abort the operation, clear the status message (required if you want to try again later) and raise an exception. Future improvements should log the status message from the telescope (logStatus, to be done) whenever there is an event (Warning, Info, etc...). 

Also implemented the function "getSensors" that reads temperature sensors from the telescope. It is later used in getMetadata to include this information in the header. I'm not sure this is the best way to implement getMetadata, (suggestions for a later PR ;))?

### CODE REVIEW

**Comment by ankanaan** [comment]
good job,

it seems to me some of these things could be useful for any telescope.  Am
I right sir?  How hard would it be to implement them at the telescope
level?  Or have you already done so?

cheers,

Antonio

**Comment by tribeiro** [comment]
Most (if not all) of the changes are really system dependent. The slewing and unparking where made to comply with the procedures suggested by Astelco.

**Comment by wschoenell** [comment]
Reviewed the code and it is okay to merge. Astelco is still under development, so I think that we should look more carefully at the next PR or so. chimera-focus has minor changes, without change on the code. openCover and closeCover were added to the telescope interface, which it is okay too.

**Comment by wschoenell** [comment]
Closed by #62

**Pull request closed without merging**
