### PR TITLE
Remove XEphem controller

### PR DESCRIPTION
**Pull request by wschoenell**
Removes XEphem controller. It was moved to a plugin on https://github.com/astroufsc/chimera-xephem/

### CODE REVIEW

**Comment by wschoenell** [comment]
Tested on my mac with the latest version of XEphem (3.7.6) and it works. Screenshots on plugin repository. Closing in a week if nobody manifests.

**Comment by phsilva** [comment]
No need to wait on this, merge if you want.

**Comment by phsilva** [comment]
Just noticed on chimera-xephem that you preserving the git history of files, nice move. Are you using git filter-branch or something similar? Are the other repos being created like this one?

**Comment by wschoenell** [comment]
Yes. I did this on all modules that I moved to a plugin. Here, for example, I used:

	git filter-branch \
		--prune-empty \
		--index-filter ' \
			git ls-tree -z -r --name-only --full-tree $GIT_COMMIT \
			| grep -z -v -i "^src/chimera/controllers/xephem.py$" \
			| gxargs -0 -r git rm --cached -r \
		' \
		-- \
		--all

 Then added the chimera repo on the chimera-template as a remote, and pull.

**Comment by phsilva** [comment]
Nice, well done.

**Pull request merged**
