### PR TITLE
Remove serial devices from chimera

### PR DESCRIPTION
**Pull request by wschoenell**
This PR removes ALL serial devices from chimera. They were moved to the chimera-serial plugin: https://github.com/astroufsc/chimera-serial

### CODE REVIEW

**Comment by phsilva** [comment]
Not sure about this, not because removing it would not make sense, but packing all those completely unrelated code in one repo just because of pyserial dependencies looks weird from user point of view. For instance, meade.py deserve a chimera-meade, and maybe this is true for other instruments as well. That's the consequence of modularization, more modules.

**Comment by ankanaan** [comment]
"packing all those completely unrelated code in one repo just because of
pyserial dependencies looks weird from user point of view."

I agree with PH

**Comment by wschoenell** [comment]
I understand your concerns. Can we leave the pyserial-dependant code on one repository like chimera-serial and make aliases to the chimera-meade chimera-optetcfs and so on? I was thinking on doing something like what this people does:
https://github.com/ionelmc/pypi-alias

So, for the user, when they try pip install chimera-meade and the other it will install chimera-serial with all the serial modules while for the programmer, it will be more easy to handle/contribute on a centralized repository. As you can check, there could be an advantage to centralize the pyserial read/write calls on one framework. What do you think?

**Comment by phsilva** [comment]
The serial drivers you touch here do not share code, so I don't see the benefit. I would have a repository/module for each brand (-meade, -jmi, -optec -lna) and leave dcfocuser in main chimera as it does not depend on pyserial anyway.

I know it is more trouble with lots of modules, but then I will never have to explain people why they are together anyway.

**Comment by phsilva** [comment]
And also, remember that most if not all instruments you touch here can and do have non serial implementations. We have a PR for Ethernet support on Meade for months. So the idea of chimera-serial will became even unclear in a short time.

**Comment by wschoenell** [comment]
ok... I will split on different plugins before merging.

**Comment by wschoenell** [comment]
I reversed the dcfocuser deletion and made separated repositories to each instrument removed from the repo on this PR. They are listed below.

https://github.com/astroufsc/chimera-jmismart232
https://github.com/astroufsc/chimera-meade
https://github.com/astroufsc/chimera-optec
https://github.com/astroufsc/chimera-lna

**Pull request merged**
