### PR TITLE
Add the ability to include camera rotation to the image WCS. 

### PR DESCRIPTION
**Pull request by tribeiro**
Definition of the rotation matrix is found here: http://www.astro.iag.usp.br/~moser/notes/GAi_FITSimgs.html.

### CODE REVIEW

**Comment by phsilva** [comment]
Might be worth adding this link into the code as a comment, probably useful for future references.

**Comment by tribeiro** [comment]
Done...

**Comment by wschoenell** [comment]
Since we are adding more complexity to the WCS and we already had some bugs by doing it "by hand" the keywords to the fits header, why don't we add an property `wcs` to the `Image` object which is an WCS object from astropy, then, inside the `getMetadata()`, we just append to the headers the content of the `image.wcs.to_header()`?

Something like this:
http://astropy.readthedocs.org/en/latest/wcs/#building-a-wcs-structure-programmatically

**Comment by tribeiro** [comment]
Can We accept this change now and discuss this in a different thread?

Em quinta-feira, 23 de julho de 2015, William Schoenell <
notifications@github.com> escreveu:

> Since we are adding more complexity to the WCS and we already had some
> bugs by doing it "by hand" the keywords to the fits header, why don't we
> add an property wcs to the Image object which is an WCS object from
> astropy, then, inside the getMetadata(), we just append to the headers
> the content of the image.wcs.to_header()?
>
> Something like this:
>
> http://astropy.readthedocs.org/en/latest/wcs/#building-a-wcs-structure-programmatically
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/pull/89#issuecomment-124285928>.
>


-- 
Sent from Mobile

**Comment by wschoenell** [comment]
Okay. I have tested this and it is working. I also ran `wcslint` tool and it works. I think that we can accept this PR for now, but if there are more parameters to be added to the WCS calculations, the way to go is discussing them on #93.

**Pull request merged**
