### PR TITLE
Remove SI driver. 

### PR DESCRIPTION
**Pull request by tribeiro**
This was moved to an external plugin.

### CODE REVIEW

**Comment by wschoenell** [comment]
I think that the external plugin which you refer is https://github.com/astroufsc/chimera-t80cam.

Is the name because this type of camera does not have filter wheels? Is it possible to split camera driver from the filter wheel driver and have two different plugins, i.e. chimera-si and chimera-soluniawheel?

I think that to get this we probably need to change the core to override the methods of the camera when you have a `filter_wheel` option.

An example of how configuration could be set could be:

	camera:
	  name: st7
	  type: SBIG
	  filter_wheel: fwheel

	filterwheel:
	  name: fwheel
	  type: MyCustomFilterWheel
	  filters: R G B RGB CLEAR

What you think?

**Comment by ankanaan** [comment]
I like the config file.  One entry for camera, one entry for filterwheel.

Still, one driver needs to know about the other, either the camera sends
info to the filterwheel or viceversa.

In a logical sense I think it would be ideal if these things could be
separated and let chimera control both.  We know this is impossible -
because of the shutter - so we are letting the camera trigger the
filterwheel shutter.  As for the filters, are we doing them directly from
chimera?

A

On Thu, Jul 16, 2015 at 6:17 AM, William Schoenell <notifications@github.com

**Comment by tribeiro** [comment]
@wschoenell, that is more or less what is going to happen. The driver for controlling the SI and the filter wheel are developed separately. I will put them together later. The scheme is slight different than what you are suggesting because the way chimera handle things. 

I am not sure I understand what @ankanaan means. As far as driver development goes, there is currently no issue. Chimera is able to control the camera (SI+FilterWheel+Shutter) as a one piece of hardware.

Can we merge this and discuss it in another thread?

**Comment by wschoenell** [comment]
Ok. I created an issue on astroufsc/chimera-t80cam#1 to address this issue.

**Pull request merged**
